### ISSUE TITLE
How to generate modelnet40_ply_hdf5_2048

### ISSUE THREAD

**Issue by Jihao-Li** [dkoguciuk/mesh2pointcloud#1]
Thank you for your contribution.
Could you please tell me how to generate modelnet40_ply_hdf5_2048 from original ModelNet40 downloaded from `http://3dshapenets.cs.princeton.edu/`?
Thank you very much!

**Comment by dkoguciuk** [comment]
Hi Jihao,

everything is in the readme: for now, only random sampling is implemented, so you won't get `modelnet40_ply_hdf5_2048` just like PointNet is using. To get more or less the same point clouds you'd need to use FPS sampling. You could, of course, use my repo as a base to implement this and submit PR ;)

Please close the issue if I've answered your question.

Best,
Daniel
