### ISSUE TITLE
Colored Point Cloud

### ISSUE THREAD

**Issue by YilmazKadir** [dkoguciuk/mesh2pointcloud#2]
Hi,
Are these generated point clouds colored or just grey level points? If not, do you plan to add color information to the generated point clouds?

**Comment by dkoguciuk** [comment]
Hi @YilmazKadir ,

no color information is processed ATM and unfortunately I don't have much time to extend this project. But if you do, please feel free to propose a pull request with the changes :) 

Best,
D

**Comment by dkoguciuk** [comment]
Closing, feel free to reopen, if you have other questions :slightly_smiling_face:
